employee/employee/employee/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('emplyeeapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                           document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root = settings.MEDIA_ROOT)

employee/employee/emplyeeapp/urls.py
from . import views
from django.urls import path
app_name='emplyeeapp'

urlpatterns = [
    path('', views.fn_home, name='fn_home'),
    path('register/',views.fn_register, name='fn_register'),
    path('add/',views.fn_add, name='fn_add'),
    path('login/',views.fn_login, name='fn_login'),
    path('emplogin/',views.fn_Emplogin,name='fn_Emplogin'),
    path('logout',views.fn_logout, name='fn_logout'),
    path('emplist',views.fn_emplist, name='fn_emplist'),
    path('view/<int:empid>/',views.fn_view,name='view')

]

employee/employee/emplyeeapp/models.py
from django.db import models

# Create your models here.

class Employee(models.Model):
    name = models.CharField(max_length=250)
    image = models.ImageField(upload_to='gallery')
    phone = models.CharField(max_length=13,unique=True)
    address = models.CharField(max_length=500)
    email = models.EmailField(max_length=70,unique=True)
    password = models.CharField(max_length=50)

    def __str__(self):
        return self.name

employee/employee/emplyeeapp/views.py
from django.contrib import auth,messages
from django.shortcuts import render, redirect
from .models import Employee
from django.contrib.auth.models import User
# Create your views here.

def fn_home(request):
    workers=Employee.objects.all()
    workers_count=workers.count()
    return render(request,'home.html',{'workers_count':workers_count})
def fn_register(request):
    return render(request,'register.html')
def fn_login(request):
    return render(request,'login.html')
def fn_emplist(request):
    emp_list = Employee.objects.all()
    return render(request, 'employeeList.html', {'emp_list': emp_list})
    # return render(request,'employeeList.html')
def fn_view(request,empid):
    emp_obj=Employee.objects.get(id=empid)
    return render(request,'view.html',{'emp':emp_obj})

def fn_add(request):
    if request.method == 'POST':
        EmpName = request.POST.get('txtEmpName')
        # image = request.FILES['img']
        Image = request.FILES.get('img')
        Phone = request.POST.get('txtPhone')
        Address = request.POST.get('txtAdderss')
        Email = request.POST.get('txtEmail')
        Password = request.POST.get('txtPassword')
        emp_obj = Employee(name=EmpName,image=Image,phone=Phone,address=Address,email=Email,password=Password)
        emp_obj.save()
        user = User.objects.create_user(username=Email, first_name=EmpName,
                                        email=Email, password=Password)
        user.save();
        return redirect('/')
    return render(request,'register.html')

# def fn_allemp(request):
#     emp_list = Employee.objects.all()
#     return render(request,'employeeList.html',{'emp_list':emp_list})

def fn_Emplogin(request):
    if request.method == 'POST':
        Username=request.POST.get('txtUsername')
        Password = request.POST.get('txtPassword')
        user = auth.authenticate(username=Username, password=Password)
        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            messages.info(request, 'Invalid Credentials')
    return render(request, 'login.html')

def fn_logout(request):
    auth.logout(request)
    return redirect('/')

employee/employee/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
<div class="container-fluid container">
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/propper.min.js' %}"></script>
</body>
</html>

employee/employee/templates/employeeList.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
        <th scope="col">Number</th>
    </tr>
  </thead>
  <tbody>
{% for emp in emp_list %}
    <tr>
      <td>{{ emp.id }}</th>
      <td>{{ emp.name }}</td>
      <td>{{ emp.email }}</td>
      <td>{{ emp.phone }}</td>
      <td><a class="btn btn-primary btn-sm" href="{% url 'emplyeeapp:view' emp.id %}">View More</a></td>
    </tr>
{% endfor %}
  </tbody>
</table>
{% endblock %}

employee/employee/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer" style="margin-top: 100px;">
  <p class="text-center">&copy; ABC Company Pvt Ltd. All Rights Reserved</p>
</div>

employee/employee/templates/header.html
{% load static %}
<div><br>
    <center>
        <a href="">
            <img src="{% static 'image/logo.png' %}" alt="logoimg" width="100px" height="60px">
        </a>
        <h3 class="text-center">ABC Pvt Ltd.</h3><br>
    </center>
    <br>

</div>

employee/employee/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
 <div>


  <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block" src="{% static 'image/slide.jpg' %}" alt="image" width="1400px;" height="300px;">
    </div>
    </div>
  </div>
</div>
<br>
     {% if user.is_authenticated %}
     <h3>Welcome  {{user.first_name}}</h3>
     {% endif %}
<br>
    <p class="text-justify">This is revolutionizing the way we all shop in India. Why do you want to hop from one store to another in search of the latest phone when you can find it on the Internet in a single click? Not only mobiles. Everything you can possibly imagine, from trending electronics like laptops, tablets, smartphones, and mobile accessories to in-vogue fashion staples like shoes, clothing and lifestyle accessories; from modern furniture like sofa sets, dining tables, and wardrobes to appliances that make your life easy like washing machines, TVs, ACs, mixer grinder juicers and other time-saving kitchen and small appliances; from home furnishings like cushion covers, mattresses and bedsheets to toys and musical instruments, we got them all covered. You name it, and you can stay assured about finding them all here. For those of you with erratic working hours, this is your best bet. Shop in your PJs, at night or in the wee hours of the morning.</p>
<br>
<div class="container">
<div class="row">
    <div class="col-sm">
        <div class="card text-center" style="width: 15rem; height: 5rem;">
          <div class="card-header bg-info text-white">
            Statistics
          </div>
          <div class="card-body col-sm">
              <h6 class="card-title">Staff<i class="fas fa-user"></i> <strong>{{ workers_count }}</strong></h6>
          </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

employee/employee/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<form action="{% url 'emplyeeapp:fn_Emplogin' %}" method="post">
    {% csrf_token %}
<div class="form">
<div class="container"><br>
    <div class="page-content" id="divContent">
        <div class="page-header">
                <h1>
                    Login here..
                </h1><br>
        </div>
        <div class="row">
            <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right">
                        Mail Id<span class="required" style="color:red;">*</span>
                    </label>
                    <div class="col-xs-12 col-sm-9">
                        <div class="input-group col-xs-12 col-sm-9">
                            <input type="text" class="form-control input-sm" name="txtUsername" placeholder="Enter your email id">
                        </div>
                    </div>
                </div>
        </div>
<br>
       <div class="row">
            <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right">
                        Password<span class="required" style="color:red;">*</span>
                    </label>
                    <div class="col-xs-12 col-sm-9">
                        <div class="input-group col-xs-12 col-sm-9">
                            <input type="text" class="form-control input-sm" name="txtPassword" placeholder="Enter your password">
                        </div>
                    </div>
                </div>
        </div>
<br>
        <div class="row">
            <div class="form-group">
                    <div class="col-xs-12 col-sm-9">
                        <div class="input-group col-xs-12 col-sm-9">
                            <input type="submit" name="Login" class="btn btn-primary">
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <h5>Login to access this website!</h5>
                        </div>
                    </div>
                </div>
        </div>
    </div>
</div>
</div>
</form>
{% endblock %}

employee/employee/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'emplyeeapp:fn_home' %}">Home</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href=" {% url 'emplyeeapp:fn_emplist' %} ">Employee_List</a>
        </li>
        {% endif %}
      </ul>

    </div>
    {% if user.is_authenticated %}
    <form class="d-flex" action="#">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search"  aria-label="Search">
        <button class="btn btn-outline-success">
          <i class="fa fa-search"></i>
        </button>
      </form> &nbsp;&nbsp;
     <a class="btn btn-secondary" href="{% url 'emplyeeapp:fn_register' %}" role="button">Add Employee</a>&nbsp;&nbsp&nbsp;&nbsp;
    <a class="btn btn-secondary" href="{% url 'emplyeeapp:fn_logout' %}" role="button">Logout</a>
    {% else %}
    <a class="btn btn-secondary" href="{% url 'emplyeeapp:fn_login' %}" role="button">Login</a>
    {% endif %}

  </div>
</nav>
<br>

employee/employee/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form action="{% url 'emplyeeapp:fn_add' %}" method="post">
    {% csrf_token %}
<div class="form">
<div class="container"><br>
    <div class="page-content" id="divContent">
        <div class="page-header">
                <h1>
                    Reistration Form
                </h1><br>
            </div>
        <div class="row">
            <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right">
                        Employee Name<span class="required" style="color:red;">*</span>
                    </label>
                    <div class="col-xs-12 col-sm-9">
                        <div class="input-group col-xs-12 col-sm-9">
                            <input type="text" class="form-control input-sm" name="txtEmpName" placeholder="Employee Name">
                        </div>
                    </div>
                </div>
        </div>
<br>
        <div class="row">
            <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right">
                        Image<span class="required" style="color:red;">*</span>
                    </label>
                    <div class="col-xs-12 col-sm-9">
                        <div class="input-group col-xs-12 col-sm-9">
                            <input type="file" name="img"  class="form-control">
                        </div>
                    </div>
                </div>
        </div>

<br>
          <div class="row">
            <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right">
                        Phone<span class="required" style="color:red;">*</span>
                    </label>
                    <div class="col-xs-12 col-sm-9">
                        <div class="input-group col-xs-12 col-sm-9">
                            <input type="text" class="form-control" name="txtPhone" placeholder="Phone Number">
                        </div>
                    </div>
                </div>
        </div>
<br>
         <div class="row">
            <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right">
                        Address<span class="required" style="color:red;">*</span>
                    </label>
                    <div class="col-xs-12 col-sm-9">
                        <div class="input-group col-xs-12 col-sm-9">
                            <input type="text" class="form-control" name="txtAdderss" placeholder="Address">
                        </div>
                    </div>
                </div>
        </div>
<br>
          <div class="row">
            <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right">
                        Email<span class="required" style="color:red;">*</span>
                    </label>
                    <div class="col-xs-12 col-sm-9">
                        <div class="input-group col-xs-12 col-sm-9">
                            <input type="email" class="form-control" name="txtEmail" placeholder="Email Id">
                        </div>
                    </div>
                </div>
        </div>
<br>
          <div class="row">
            <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right">
                        Password<span class="required" style="color:red;">*</span>
                    </label>
                    <div class="col-xs-12 col-sm-9">
                        <div class="input-group col-xs-12 col-sm-9">
                            <input type="password" class="form-control" name="txtPassword" placeholder="Password">
                        </div>
                    </div>
                </div>
        </div>
<br>
        <div class="row">
            <div class="form-group">
                    <div class="col-xs-12 col-sm-9">
                        <div class="input-group col-xs-12 col-sm-9">
                            <input type="submit" class="btn btn-primary">&nbsp;&nbsp;&nbsp;&nbsp;
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <a href="{% url 'emplyeeapp:fn_login' %}">Already have an account...? Login here !</a>
                            <br>&nbsp;&nbsp;&nbsp;&nbsp;
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<!--                            {% for msg in messages %}-->
<!--                            <h5 style="color:red;">{{msg}}</h5>-->
<!--                            {% endfor %}-->
                        </div>
                    </div>
                </div>
        </div>
<br>
    </div>
    </div>
</div>
</form>
{% endblock %}

employee/employee/templates/view.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="cotainer-fluid border">
    <br>
     <div class="row">
        <div class="col-sm text-center">
            {% if emp.image %}-->
                <img src="{{ emp.image.url }}" class="rounded" alt="image">
            {% else %}
                <img src="{% static 'image/employee.png' %}" class="rounded" alt="image">
            {% endif %}
        </div>
        <div class="col-md-8">
            <span><strong>EmpId :</strong></span>&nbsp;&nbsp;{{ emp.id }}<br>
            <span><strong>Name :</strong></span>&nbsp;&nbsp;{{ emp.name }}<br>
            <span><strong>Phone :</strong></span>&nbsp;&nbsp;{{ emp.phone }}<br>
            <span><strong>Email :</strong></span>&nbsp;&nbsp;{{ emp.email }}<br>
            <span><strong>Address :</strong></span>&nbsp;&nbsp;{{ emp.address }}<br>
        </div>
    </div>
<!--    <div class="text-left">-->
<!--        {% if emp.image %}-->
<!--        <img src="{{ emp.image.url }}" class="rounded" alt="image">-->
<!--        {% else %}-->
<!--        <img src="{% static 'image/employee.png' %}" class="rounded" alt="image">-->
<!--        {% endif %}-->
<!--    </div>-->

</div>
<!--{{ emp.name }}<br>-->
<!--{{ emp.email }}-->
{% endblock %}